#ifndef FINAL_PROJECT_ASTEROID_H
#define FINAL_PROJECT_ASTEROID_H

#include "./asteroidStructure.h"

#define MAX_ASTEROID_RADIUS 16
#define MIN_ASTEROID_RADIUS 4
#define nASTEROID_VERTICES 8

#endif //FINAL_PROJECT_ASTEROID_H
